// app/layout.tsx (still a Server Component)
import './globals.css'
import type { ReactNode } from 'react'
import { AllProvider } from '@/context/Allcontext'
import ClientLayout from '@/components/ClientLayout '

export const metadata = {
  title: 'My Appw',
  description: 'Generated by Next.js',
}

interface RootLayoutProps {
  children: ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <AllProvider>
          <ClientLayout>
            {children}
          </ClientLayout>
        </AllProvider>
      </body>
    </html>
  )
}
