import { AllProvider } from '@/context/Allcontext'
import Hero from '@/components/hero'
import './globals.css'
import type { ReactNode } from 'react'
import Navbar from '@/components/navbar'

export const metadata = {
  title: 'My Appw',
  description: 'Generated by Next.js',
}

interface RootLayoutProps {
  children: ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <AllProvider>
          <Navbar /> {/* ✅ Appears on all pages */}
          <Hero />   {/* ✅ Appears on all pages */}
          {children}
        </AllProvider>
      </body>
    </html>
  )
}
